# Generated by Django 5.1.2 on 2024-11-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("street_number", models.IntegerField()),
                ("street_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("registration_date", models.DateField()),
                ("party_affiliation", models.CharField(max_length=10)),
                ("precinct_number", models.IntegerField()),
                ("voter_score", models.IntegerField()),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
            ],
        ),
    ]
