# Generated by Django 5.1.2 on 2024-11-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voter_analytics", "0002_alter_voter_voter_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="dob",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="registration_date",
            new_name="date_of_registration",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="voter_id",
        ),
        migrations.AddField(
            model_name="voter",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="zip_code",
            field=models.CharField(default="00000", max_length=10),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="voter",
            name="street_number",
            field=models.CharField(max_length=10),
        ),
    ]
