# Generated by Django 5.1.2 on 2024-11-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voter_analytics", "0003_rename_dob_voter_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
    ]
