# Generated by Django 5.1.2 on 2024-12-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_category_attendance_course_category_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "instructor"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
    ]
