# Generated by Django 5.1.2 on 2024-12-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_user_is_active_alter_attendance_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "instructors"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "students"},
                on_delete=django.db.models.deletion.CASCADE,
                to="project.user",
            ),
        ),
    ]
