# Generated by Django 5.1.2 on 2024-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_discussionthread_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionthread",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
